### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by gl-eb**
This is a draft PR to test possible fixes to the `manybuild_linux` jobs.

### CODE REVIEW

**Comment by gl-eb** [comment]
The `ci` workflow does not work on pull requests because `GITHUB_REPO` points to `htseq/htseq` but the PR branch is on a fork, e.g. `gl-eb/htseq`.
`actions/checkout` should take care of this, but v4 does not work because it depends on node20. Thus v3 should be the way to go. Currently the next issue are the file system paths for the build

**Comment by gl-eb** [comment]
Using the `actions/checkout@v3` with `path: htseq` turns out to be a drop-in replacement for the previous cloning steps. All subsequent steps can remain the same.

**Comment by gl-eb** [comment]
Sorry to ping you gain @iosonofabio. The changes to CI in this PR should hopefully put an end to the failed checks seen in other PRs. Should you be happy with them and merge the PR, I can rebase #72 to include the changes.

Also sorry for the messy history of force pushing. The commit history is clean at least.

**Comment by iosonofabio** [comment]
Thanks for pinging. I'll review hopefully before EoW

**Pull request merged**
