### PR TITLE
issue #83 - 'tag' attributes lost in GTF parsing

### PR DESCRIPTION
**Pull request by davmlaw**
Fix for issue #83 'tag' attributes lost in GTF parsing  

I agree with your idea of:

> I'd be for a list of pairs: straight over from the file format and no complex and arbitrary decisions. The users who need this feature can convert to sets etc themselves if they want

So the change is to add ```GenomicFeature.attr_tuples```, default behavior remains unchanged

And the user can turn it into a set (or comma separated list or whatever via)

```
from collections import defaultdict

attr_set = defaultdict(set)
for tag, value in feature.attr_tuples:
    attr_set[tag].add(value)

In [6]: attr_set
Out[6]: 
defaultdict(set,
            {'gene_id': {'ENSG00000275405'},
             'gene_version': {'1'},
             'transcript_id': {'ENST00000619109'},
             'transcript_version': {'1'},
             'exon_number': {'1'},
             'gene_name': {'U1'},
             'gene_source': {'ensembl'},
             'gene_biotype': {'snRNA'},
             'transcript_name': {'U1.26-201'},
             'transcript_source': {'ensembl'},
             'transcript_biotype': {'snRNA'},
             'exon_id': {'ENSE00003747303'},
             'exon_version': {'1'},
             'tag': {'Ensembl_canonical', 'basic'},
             'transcript_support_level': {'NA'}})
```

**Benchmark**

I ran the code before and after, counting attributes on Homo_sapiens.GRCh38.112.gtf.gz

Mean time for 10 runs before: 99.38s
Mean time for 10 runs after: 101.4s (2% slower)

```
from collections import Counter
import gzip
import time
from HTSeq import GFF_Reader

def get_counts_and_time(filename):
        tag_counts = Counter()

        with gzip.open(filename) as f:
            start = time.time()
            for feature in GFF_Reader(f):
                # print(feature.attr_tuples)
                if tag := feature.attr.get("tag"):
                    tag_counts[tag] += 1
            end = time.time()
            return tag_counts, end - start
    

filename = "/data/annotation/cdot_generation/ensembl/Homo_sapiens.GRCh38.112.gtf.gz"

run_times = []
for i in range(10):
    tag_counts, seconds = get_counts_and_time(filename)
    print(tag_counts)
    run_times.append(seconds)
```

before:

```
[97.41733765602112,
 95.64415717124939,
 98.04735779762268,
 98.52129173278809,
 96.54414200782776,
 101.04121732711792,
 96.98768925666809,
 95.2579436302185,
 108.78449988365173,
 105.6002185344696]

In [8]: np.mean(run_times)
Out[8]: 99.38458549976349
```

after:

```
[99.92735409736633,
 101.9016580581665,
 107.49527096748352,
 105.03898191452026,
 106.10472989082336,
 97.05439949035645,
 97.97948980331421,
 101.27231287956238,
 98.98224806785583,
 98.2618293762207]

In [5]: np.mean(run_times)
Out[5]: 101.40182745456696
```

### CODE REVIEW

**Comment by iosonofabio** [comment]
Thank you for the PR. A few comments to get the ball rolling:

- not sure about the linker issue, perhaps something with manylinux and node updates on GitHub actions
- not sure why you are touching `__iter__`, as that's the default action and it should not change?

I'll take a closer look asap, not really a lot of bandwidth to debug linker issues ATM because I just had a baby

**Comment by davmlaw** [comment]
Congratulations! No hurry!

I've used my fork to solve my problem but happy to change it to whatever you think best suits the library

The change in ```__iter__``` is to add an extra field ```GenomicFeature.attr_tuples``` - default behavior is preserved by still having attr stay exactly the same

There may be a very low memory overhead (having a different data structure with shared strings between tuples/dict) and a very small (2%) performance hit according to my benchmarks

**Comment by iosonofabio** [comment]
Thanks for your understanding! I'll take a look asap

**Comment by iosonofabio** [comment]
Runner errors might be https://github.com/actions/checkout/issues/1809

Updating our docker containers should help if so. I'll try later today or you can try it

**Comment by davmlaw** [comment]
@iosonofabio - nice meeting you at the conference!

I updated the docs for the new ```attr_tuples``` field so it matches what is found via ```dir``` now

**Comment by iosonofabio** [comment]
Was great! I'll try to push to this branch tonight if I manage

**Comment by iosonofabio** [comment]
Thanks @davmlaw - finally made it! Thanks again! Will include in the next release, as soon as I'm back and *not* in a dark room with a crying baby ;-)

**Pull request merged**
