### PR TITLE
#38 - "auto" GenomicArray creates finite length chromosome if 1st acc…

### PR DESCRIPTION
**Pull request by davmlaw**
test_access_out_of_range demonstrates the problem - the second loop is the same as the first except it has a line ```genomic_array[known_iv] = "test"
``` - calling the setter first before the getter used to cause the test to fail with ```IndexError: stop too large```

After making the change, I also had to modify the bedgraph file test. I believe this is due to an unrelated bug (which I haven't fixed) - write_bedgraph_file tries to deal with infinite sized chromosomes via:

```
if iv.start == -sys.maxsize - 1 or iv.end == sys.maxsize:
```

The code checks for ```start = sys.maxsize-1``` used to represent infinity but I can't see anywhere where it sets it that way, add_chrom by defaults to setting start to 0

### CODE REVIEW

**Comment by iosonofabio** [comment]
Thank you. Would you mind trying to fix that bug in this same PR since you're on it?

**Comment by davmlaw** [comment]
Hi, I'm not sure exactly what to do here.

Having the magic value of end=sys.maxint makes sense for +infinity but negative chromosome coordinates don't make sense and IMO shouldn't be allowed.

Maybe you could check for empty value around 0, or perhaps make a flag (separate from magic value in start) that flags "empty at the beginning of a chromosome"

FYI this change didn't cause the bedgraph issue where it writes empty values from 0, it just caused it to be revealed in the test case by making it also happen for "auto" GenomicArrays

It used to happen before:

```
import HTSeq
ga = HTSeq.GenomicArray(["1"])
iv = HTSeq.GenomicInterval("1", 128198270, 128212028, "+")
ga[iv]  = 1
ga.write_bedgraph_file("foo.txt", "+")
```

```
In [13]: cat foo.txt                                                                                                                                                  
track type=bedGraph
1	0	128198270	0.0
1	128198270	128212028	1.0
```

**Comment by iosonofabio** [comment]
It's the parser I'm referring to, not the writer. Anyway, I'll think about this problem and see if I can come up with a decent solution. If you have any ideas in the meanwhile, please push them to this PR. In any case, we won't change the bedgraph file.

**Comment by davmlaw** [comment]
Ah ok, yes I agree that the previous bedgraph functionality was good for the reason you stated (difference between unknown and zero) I've reverted the bedgraph test and example file.

The difficulty is the bedgraph code relies on the finite auto chromosome behavior, which was introduced in the same commit, but that breaks existing code which depends on the library (it caused my code to crash upgrading to 1.99.2 see #38)

To get them both to work, I added a flag auto_chroms_infinite_size to initialise GenomicArray - and made ```from_bedgraph_file``` use ```auto_chroms_infinite_size=False```

I made it default to True so it preserves the behavior prior to all versions earlier than Nov 20, 2021

**Comment by iosonofabio** [comment]
I'm not super happy of adding optional arguments instead of sensible default behaviours. Let me wrap up the revisions for this paper in the next week or two and then I'll come back to this.

**Comment by iosonofabio** [comment]
Alright, I added a new mode for `GenomicArray` called `auto-write`, which creates chromosomes of appropriate size when setting values but never when getting values from nonexistent chromosomes. The bedgraph parser uses this mode now.

Old behaviour and your test work because  the "auto" mode is reverted, however the new "auto-write" is a little less sloppy. Note that the current "auto" mode might disappear in the future, as requesting a chromosome that does not have data defaults the whole chromosome to zero and that looks like a clear antipattern. The recommended pattern would be:

```python
ga = HTSeq.GenomicArray('auto-write')
ga[HTSeq.GenomicInterval(chrom, 0, sys.maxsize, strand=strand)] = 0 # or whatever other default value
```

This way you explicitely define the data before querying, but you are not required to create a whole `ChromVector` yourself.

**Comment by iosonofabio** [comment]
[BUG] GenomicArray 'auto' chrom feature acquires an 'auto-write' sibling for clarity.

**Pull request merged**
